# docker-compose.yml
version: '3'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SPA
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    depends_on:
      - socket

  socket:
    build: 
      context: ./Socket
    ports:
      - "3001:3001"
    volumes:
      - ./Socket:/app
    environment:
      - NODE_ENV=development

  app:
    build: 
      context: ./App
    ports:
      - "19000:19000"  
      - "19001:19001"  
      - "19002:19002"   
      - "8081:8081" 
    volumes:
      - ./App:/app
    environment:
      - NODE_ENV=development

  migration:
    build: 
      context: ./Migration
    volumes:
      - ./Migration:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      # - app

  api:
    build: 
      context: ./API
    ports:
      - "3000:3000"
    volumes:
      - ./API:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - migration 
      - socket
      # - app

volumes:
  db_data: